# Generated by Django 3.1.6 on 2021-02-06 23:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, null=True)),
                ('slack_id', models.CharField(max_length=80, null=True)),
            ],
        ),
    ]
