# Generated by Django 3.1.6 on 2021-02-06 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dessert_name', models.CharField(max_length=80, null=True)),
                ('category', models.CharField(choices=[('Carnivoro', 'Carnivoro'), ('Vegetariano', 'Vegetariano'), ('Vegano', 'Vegano')], max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Carnivoro', 'Carnivoro'), ('Vegetariano', 'Vegetariano'), ('Vegano', 'Vegano')], max_length=200, null=True)),
                ('dessert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.dessert')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=80, null=True)),
                ('category', models.CharField(choices=[('Carnivoro', 'Carnivoro'), ('Vegetariano', 'Vegetariano'), ('Vegano', 'Vegano')], max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salad_name', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('lunch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.lunch')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(null=True)),
                ('lunchs', models.ManyToManyField(to='menu.Lunch')),
            ],
        ),
        migrations.AddField(
            model_name='lunch',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.meal'),
        ),
        migrations.AddField(
            model_name='lunch',
            name='salad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.salad'),
        ),
    ]
